### ISSUE TITLE
Chunked requests still have content-length ?

### ISSUE THREAD

**Issue by malliapi** [chimurai/http-proxy-middleware#156]
It seems that chiunked requests are not correctly handled?

**Comment by chimurai** [comment]
The scarse information you're providing is not really helpful.

Please follow the [CONTRIBUTING guidelines](https://github.com/chimurai/http-proxy-middleware/blob/master/CONTRIBUTING.md#report-issues) or use the [ISSUE template](https://github.com/chimurai/http-proxy-middleware/blob/master/ISSUE_TEMPLATE.md).

Thanks.

[_How to Ask Good Coding Questions That Get Great Answers..._](http://zellwk.com/blog/asking-questions/)

**Comment by chimurai** [comment]
Would be great if you can provide a minimal example.

**Comment by chimurai** [comment]
Closing issue until further information is provided.

Feel free to reopen.

**Comment by frankdou** [comment]
@chimurai  

I was trying to proxy a page from node server(via  http-proxy-middleware) to vue-cli proxy( seems also http-proxy-middleware) then to browser.

When  i visit node server, everything is expected.
Then i visit vue-cli server, browser would got error of HPE_UNEXPECTED_CONTENT_LENGTH.

Finally fixed by:
```
onProxyRes: (proxyRes, req, res) => {
                const isNotCorrect = res.getHeader('content-length') && proxyRes.headers['transfer-encoding'];

                if (isNotCorrect) {
                    res.removeHeader('content-length');
                } 
            },
```

ref：https://stackoverflow.com/questions/35525715/http-get-parse-error-code-hpe-unexpected-content-length
