### ISSUE TITLE
Unable to transform content on receiving data

### ISSUE THREAD

**Issue by HMDH** [chimurai/http-proxy-middleware#158]
I need to use a proxy to transform the output of the content. Why is there no callback to take in data so that I can write to it?

I've tried using transformer-proxy but I'm unable to get it to work.

For example, this doesn't work:
```
var express = require("express"),
  proxy = require("http-proxy-middleware"),
  transformerProxy = require("transformer-proxy"),
  app = express();


app.use("/", proxy({
  target: "https://someurl",
  changeOrigin: true
}));

app.use(transformerProxy((data, req, res) => { newData = data + "\n"; return newData; });
app.listen(3000, () => {
  console.log("Listening on port 3000");
});

**Comment by chimurai** [comment]
From their documentation it looks like you have to configure `transformer-proxy` before `http-proxy-middleware `

https://github.com/philippotto/transformer-proxy/blob/master/examples/simple.js

**Comment by HMDH** [comment]
I've tried it that way too.

**Comment by chimurai** [comment]
`transformer-proxy` looks somewhat outdated.

Did you try their [simple example](https://github.com/philippotto/transformer-proxy/blob/master/examples/simple.js) with the latest version of `http-proxy`?

If that works, it might also work with `http-proxy-middleware` since HPM is based on `http-proxy`

**Comment by chimurai** [comment]
Issue has gone stale; Closing issue.
Feel free to re-open.
