### ISSUE TITLE
Error occuper  while trying to proxy to : http://localhost:8080/api

### ISSUE THREAD

**Issue by oza75** [chimurai/http-proxy-middleware#181]
### Setup

* Vuejs 1.0.0 with webpack

#### My problem
I develop a little website with laravel in blackend and vuejs in front.
Thus I configure my webpack config file and I add to proxyTable object a new proxy '/api'  that target to my laravel api.  When I try to get localhost:8080/api in my browse, I get an error that tell: Error occured while trying to proxy to : localhost:8080/api . I should be redirected in http://localhost..

![capture](https://user-images.githubusercontent.com/29458652/28166516-bdb31962-67c7-11e7-92e1-1ddb8c7057e7.JPG)

**Comment by chimurai** [comment]
This means `http://localhost/api` can not be reached.

With this configuration you're basically trying to do this:
`http://localhost:8080/api` -> `http://localhost/api`

Can't tell if you `/api` is really served from `http://localhost/api`

**Comment by oza75** [comment]
I changed  target:'http://localhost' To  http://localhost:8000'  but there is the same problem when I try get http://localhost:8080/api..
http://localhost:8000' is the laravel home page!
I'm using Windows with Xamp as php Server..

**Comment by chimurai** [comment]
Does `http://localhost:8000/api` work at all? Make sure and verify that server is working.

Just remember other devs ran into similar issue with Laravel. (https://github.com/chimurai/http-proxy-middleware/issues/21#issuecomment-138132809)

Try starting your Laravel server with: `php artisan serve --host 0.0.0.0` or `php artisan serve --host 127.0.0.1`

**Comment by oza75** [comment]
I take some screenshot for more comprehension. 
![config](https://user-images.githubusercontent.com/29458652/28208609-162fdc36-687e-11e7-8adf-a78e8588f91b.JPG)
![c2](https://user-images.githubusercontent.com/29458652/28208661-62a75d1e-687e-11e7-8182-f9a4a1b44626.JPG)
![console1](https://user-images.githubusercontent.com/29458652/28208822-2ee1f452-687f-11e7-994a-9f2b07ee6c07.JPG)
![chorem](https://user-images.githubusercontent.com/29458652/28208865-6c235e64-687f-11e7-8001-3835db0b9251.JPG)

**Comment by chimurai** [comment]
What do you get when you open `http://localhost:8000/api` in your browser?

**Comment by oza75** [comment]
I get success status code:200
![api-1](https://user-images.githubusercontent.com/29458652/28211279-53de50e6-688b-11e7-899d-cfb5f4c29c24.jpg)

**Comment by chimurai** [comment]
Did you try `php artisan serve --host 0.0.0.0` as well?

Think it's something wrong with your Laravel / xamp configuration which prevents your from proxying the request.

Please try using [StackOverflow](https://stackoverflow.com) to troubleshoot your setup.

Don't think it a bug in http-proxy-middleware.
Feel free to re-open the issue if you do think it's an issue caused by http-proxy-middleware due to a bug.

**Comment by eitland** [comment]
FWIW this seems strinkingly similar to this issue over at webpack-dev-server https://github.com/webpack/webpack-dev-server/issues/744

Also webpack-dev-server uses http-proxy-middleware.

For that issue it turned out that it worked when the submitter 

- was connected to the network
- or used 127.0.0.1 in the configuration instead of localhost

also it seems this issue only occurs on Windows.

Still this seems a bit weird since Windows knows the address of localhost even when offline.

**Comment by yogeshvitkar** [comment]
Use one of below 2 solutions

1. Connect your system to the internet and execute again, it will work.

else

2. configure server proxy in the client application with localhost IP( http://127.0.0.1:8080 ) instead of http://localhost:8080

**Comment by ZMALIM** [comment]
> Utilice una de las 2 soluciones siguientes
> 
> 1. Conecta tu sistema a internet y ejecuta de nuevo, funcionará.
> 
> más
> 
> 1. configure el servidor proxy en la aplicación cliente con localhost IP ( http://127.0.0.1:8080 ) en lugar de [http: // localhost: 8080](http://localhost:8080)

Despues de horas y dias de busqueda sobre este error, me diste la solucion a este problema, gracias.
