### ISSUE TITLE
No Graceful Shutdown?

### ISSUE THREAD

**Issue by alistair-hmh** [chimurai/http-proxy-middleware#287]
### Expected behavior

Proxy closes when the parent process receives `SIGINT` or `exit`.

### Actual behavior

Proxy keeps running

### Setup

* http-proxy-middleware: `0.18.0`
* server: express `4.16.3`

#### proxy middleware configuration

```javascript
const options = {
    target: 'http://localhost:3001',
    changeOrigin: true,
    ws: true
};

const appProxy = proxy(options);
```

#### server mounting

```javascript
var app = express();

app.use('/', appProxy);
app.listen(3000);
```

Using this config, kill the app. The middleware proxy will keep running.

**Comment by geiseri** [comment]
I think the issue is that there needs to be a way to expose `proxy.close()`.  I will try to PR and see if that does it.  Right now I can use the `express-dynamic-middleware` to handle basic routes, but it will not close the websocket proxy unless you call `proxy.close()`.  See: https://github.com/nodejitsu/node-http-proxy#shutdown for the details.
