### ISSUE TITLE
How to stop sending the req after an exception being thrown 

### ISSUE THREAD

**Issue by borzoum** [chimurai/http-proxy-middleware#338]
onProxyReq: (proxyReq, req, res) => {
try{
//something
}catch(err){
 res.send(500);
}
even after sending back 500 to the caller, the proxy still tries to send the request ti the servcer.
What am I doing wrong?

**Comment by dobesv** [comment]
You didn't really give enough information, but my first guess would be that in `//something` you are doing something async, and thus your `catch` block isn't catching it.  If you use `async / await` then your `catch` block can apply, otherwise you'll have to move the error handling into the appropriate place.

**Comment by bforbis** [comment]
@borzoum, once onProxyReq event is fired, the proxyReq object has already been created and the socket to the target host is open (though no data has been sent yet).

To abort the proxied request, you could do `proxyReq.abort()`
