### ISSUE TITLE
typing for proxyRes seems to be incorrect

### ISSUE THREAD

**Issue by dylang** [chimurai/http-proxy-middleware#407]
### Steps to reproduce

Using TypeScript, this is valid but throws an error.
```ts
// options
onProxyRes: (proxyRes, req, res) => {
  const incomingCookies = proxyRes.getHeader(SET_COOKIE_HEADER);
  // etc
},
```

### Expected behavior

* TypeScript doesn't expect `proxyRes.getHeader`, `proxyRes.hasHeader`, `proxyRes.setHeader` to be methods available.
* TypeScript expects `proxyRes.headers` to be an array of strings.

### Actual behavior

```bash
 ✖  uncaughtException (an exception was thrown but not caught)  TypeError: proxyRes.getHeader is not a function
    at ProxyServer.onProxyRes (proxy.ts)
````

### Workaround

`proxyRes.headers` works as expected, so adding this code works, but it would be cleaner to just have the correct types.

```ts
// options
onProxyRes: (
  proxyRes: ServerResponse & { headers: { [name: string]: string[] } },
  req,
  res
) => {
  const incomingCookies = proxyRes.headers[SET_COOKIE_HEADER];
  // etc
},

```

I'm not sure what type the `proxyRes` should be.

#### client info

I'm using latest Express.

### Reproducible Demo

I can create one if necessary.

**Comment by chimurai** [comment]
Nice catch. I used the community types as starting point to include the types in HPM.

Looks like they have the same issue:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/http-proxy/index.d.ts#L136

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/http-proxy-middleware/index.d.ts#L38

I'm also not sure what type `proxyRes` should be; Since that `proxyRes` is coming from the `http-proxy` library.

Definitely wouldn't mind your help to make the typing more correct.
Feel free to give it a shot.

**Comment by dylang** [comment]
[Right now in this module](https://github.com/chimurai/http-proxy-middleware/blob/master/src/types.ts#L28) it's [http.ServerResponse](https://nodejs.org/api/http.html#http_class_http_serverresponse).

It seems like it should be [http.incomingMessage](https://nodejs.org/api/http.html#http_class_http_incomingmessage).

Why did you think it should be `http.ServerResponse` instead? I haven't had a chance to try this yet and could be wrong.

**Comment by chimurai** [comment]
Think it might be a booboo from my side.

**Comment by dylang** [comment]
Changing `proxyRes` to `http.IncomingMessage` fixed those types for me! Would you like a PR?

**Comment by chimurai** [comment]
That would be awesome!
