### ISSUE TITLE
target is changed to localhost on the same machine

### ISSUE THREAD

**Issue by gavihs** [chimurai/http-proxy-middleware#464]
I am using React for the Frontend and Flask for the Backend; React runs on port 443 and flask on port 5000

Both the servers are running on HTTPS with CA signed certificates

The following is my configuration

```
const proxy = require('http-proxy-middleware');

module.exports = function(app) {
    app.use( proxy( '/api/**', { target: 'https://example.com:5000/', logLevel: 'debug', changeOrigin: true } ));
}
```

I make a request for /api/login from React. The proxy forward gives the following error

`[HPM] Error occurred while trying to proxy request /api/login from example.com to https://localhost:5000 (ERR_TLS_CERT_ALTNAME_INVALID) (https://nodejs.org/api/errors.html#errors_common_system_errors)`

I have posted this in stackoverflow and there has been no response

Is there any reason why the target server would be changed to localhost?

I did the following and still could not resolve

1. Create another DNS backend.example.com and did the proxy forwarding to backend.example.com
2. Changed the hostname to example.com

Is this a Bug or am I missing something?

**Comment by AubreyHewes** [comment]
@gavihs  

* Using the proposed (when you opened the issue) [issue template](https://github.com/chimurai/http-proxy-middleware/blob/master/.github/ISSUE_TEMPLATE.md) would help.
  * Adding a [minimal repo/online example](https://github.com/chimurai/http-proxy-middleware/blob/master/.github/ISSUE_TEMPLATE.md#reproducible-demo) of your problem would help.

Assumptions:
 * your proxy `target` is not hardcoded and set via an `env` value, which defaults to localhost (for dev reasons)?
   * if so it is a configuration error
 * your proxy `target` is actually `https://localhost:5000` but that (local) server does not have a certificate with an alt name for localhost?
   * if so it is a configuration error; try `http://` instead of `https://`.

**Comment by gavihs** [comment]
@AubreyHewes - Thank you; I had not set the environment variable
