### ISSUE TITLE
lost session with multiples hosts 

### ISSUE THREAD

**Issue by leandrolimasi** [chimurai/http-proxy-middleware#60]
I use multiple host on a proxy configuration. When I call several at the same time , I 'm losing session and the rest call always returns error 204 No content.

Any idea?

**Comment by chimurai** [comment]
Please provide more info: https://github.com/chimurai/http-proxy-middleware/blob/master/CONTRIBUTING.md#report-issues

**Comment by leandrolimasi** [comment]
Sorry,

proxys configs:

 proxyMiddleware('/z14/**', {target: 'http://10.11.100.54/', changeOrigin: true, logLevel: 'debug'}),
 proxyMiddleware('/z02/**', {target: 'http://10.16.100.138/', changeOrigin: true, logLevel: 'debug'})

my localhost context is  "/z14b/"

When in my page html calls multiples request over z14 and z02, my session in z14b is lost.

**Comment by chimurai** [comment]
Don't think this is a http-proxy-middleware issue. Since it doesn't do anything with headers and cookies.

Isn't it as simple as the target servers overwriting each others session cookie.

You should be able to configure the `session cookie name` differently for each server, so the sessions won't clash and override each other...

**Comment by chimurai** [comment]
Feel free to re-open the issue, if you think it's a bug.
