### ISSUE TITLE
http2 example

### ISSUE THREAD

**Issue by korczis** [chimurai/http-proxy-middleware#79]
### Expected behavior

Example showing how to use this middleware with http2 should be provided.
### Actual behavior

No example showing how to use this middleware with http2 is provided.

**Comment by chimurai** [comment]
Haven't used it with http2 yet.
Happy to receive a PR for this.

**Comment by korczis** [comment]
@chimurai Unfortunately I was not able to make it working with https://github.com/molnarg/node-http2

**Comment by chimurai** [comment]
It will be helpful if you can share your setup / use-case.

Not sure what kind of http2 example you looking for...
- HTTP -> HTTP2
- HTTP2 -> HTTP
- HTTP2 -> HTTP2
- ...

I did found a HTTP2 -> HTTP example in the `http-proxy` issue tracker:
https://github.com/nodejitsu/node-http-proxy/pull/919#issuecomment-201569021

**Comment by korczis** [comment]
I am interested in http2 -> http2

**Comment by chimurai** [comment]
@korczis, can you please share the code / setup which failed to work?

**Comment by manueltimita** [comment]
Here's a working example, using `express` and `spdy` (don't attempt to use `http2` instead of `spdy` because it doesn't support `express` yet https://github.com/molnarg/node-http2/issues/100). 

Do not confuse the NPM package `spdy` with the SPDY protocol by Google. The latter is being deprecated, but the NPM package actually supports all protocols (HTTP/2.0, HTTP/1.1, etc).

I have been looking around, and was not sure where it was best to add an example (as README or js file, or both). Here it is for copy/paste convenience, based on the code from `examples/express/index.js`:

```javascript
/**
 * Module dependencies.
 */
var fs      = require('fs');
var express = require('express');
var spdy    = require('express');
var proxy   = require('http-proxy-middleware');

/**
 * You need SSL!
 */
var ssl = {
    cert: fs.readFileSync(`server.cert`, 'utf8'),
    key: fs.readFileSync(`server.key`, 'utf8')
}

/**
 * Configure proxy middleware
 */
var jsonPlaceholderProxy = proxy({
    target: 'http://jsonplaceholder.typicode.com',
    changeOrigin: true,
    logLevel: 'debug'
});

var app = express();

/**
 * Add the proxy to express
 */
app.use('/users', jsonPlaceholderProxy);

// replace this line with a spdy server:
// app.listen(3000); 
spdy
    .createServer(ssl, app)
    .listen(3000);
```

**Development note:** Chrome seems to always report the version as HTTP/1.1. I don't know the reason (perhaps due to self-signed cert?), but if you want to make sure it works, just use Firefox, and click on one of the connections. FF will show you that the HTTP version is 2.0 

![http2](https://cloud.githubusercontent.com/assets/4958941/17798777/754c4462-65cc-11e6-9394-fc243a58354e.PNG)

P.S. @chimurai Thanks for this great piece of software! Extremely helpful

**Comment by chimurai** [comment]
Thanks for sharing the example @manueltimita

**Comment by btkfrank** [comment]
> ```js
> var spdy    = require('express');
> ```

is it a typo?
`var spdy    = require('express');` should be `var spdy    = require('spdy');`
